from pythia.node_types import Person, Place, Occupation, Organization


example_data = [
    [Person('xavier mathew'), 'born_at', Place('hyderabad')],
    [Place('hyderabad'), 'part_of', Place('telengana')],
    [Place('telengana'), 'part_of', Place('india')],
    [Person('xavier mathew'), 'son_of', Person('mathew something')],
    [Person('mathew something'), 'born_at', Place('chennai')],
    [Place('chennai'), 'part_of', Place('tamilnadu')],
    [Place('tamilnadu'), 'part_of', Place('india')],
    [Person('xavier mathew'), 'works_as', Occupation('engineer')],
    [Person('xavier mathew'), 'works_at', Organization('compile')],
    [Organization('compile'), 'located_at', Place('bangalore')],
    [Place('bangalore'), 'part_of', Place('karnataka')],
    [Place('karnataka'), 'part_of', Place('india')],
    [Person('ankit arora'), 'works_at', Organization('compile')],
    [Person('ankit arora'), 'works_as', Occupation('engineer')],
    [Person('ankit arora'), 'born_at', Place('mumbai')],
    [Occupation('engineer'), 'same_as', Occupation('developer')],
    [Occupation('developer'), 'same_as', Occupation('programmer')],
    [Person('saint francis xavier'), 'born_at', Place('javier')],
    [Place('javier'), 'part_of', Place('navarre')],
    [Place('navarre'), 'part_of', Place('spain')],
    [Person('saint francis xavier'), 'works_as', Occupation('missionary worker')],
    [Person('saint francis xavier'), 'works_at', Organization('saint xaviers college')],
    [Person('saint fermin'), 'works_as', Occupation('missionary worker')],
    [Person('saint fermin'), 'works_at', Organization('saint fermin college')],
    [Occupation('missionary worker'), 'same_as', Occupation('priest')],
    [Organization('saint xaviers college'), 'located_at', Place('mumbai')],
    [Organization('saint fermin college'), 'located_at', Place('pamplona')],
    [Place('mumbai'), 'part_of', Place('maharashtra')],
    [Place('maharashtra'), 'part_of', Place('india')],
    [Place('pamplona'), 'part_of', Place('navarre')],
]
